language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-ssl --white-list twitter.com www.facebook.com plus.google.com www.linkedin.com img.shields.io www.paypal.me creativecommons.org scripts.sil.org choosealicense.com
